clone:
  git:
    image: envelopecity/drone-git-lfs

pipeline:
  build:
    image: centos:7.4.1708
    commands:
      - yum install -y centos-release-ceph-luminous
      - yum install -y gcc rpm-build make yum-utils epel-release glusterfs-api-devel glusterfs-devel libcephfs-devel
      - yum-builddep -y samba
      - ./localbuild -bb samba.spec
    when:
       event: [tag]
  github_release:
    image: plugins/github-release
    files:
      - "*.rpm"
    checksum:
      - md5
    secrets: [github_token]
    when:
       event: [tag]
  s3:
    image: plugins/s3
    bucket: jmdrepo
    source: "*.tar.gz"
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    path_style: false
    acl: public-read
    endpoint: https://oss-cn-beijing.aliyuncs.com
    when:
       event: [tag]

  pushbear:
    image: thesues/drone-pushbear
    url: XXXX
    secrets: [sendkey]
    when:
      event: [tag, push]
      success: false
      failure: false
      change: true
