clone:
  git:
    image: envelopecity/drone-git-lfs

pipeline:
  build:
    image: centos:7.4.1708
    commands:
      - yum install -y centos-release-ceph-luminous
      - yum install -y rpm-build make yum-utils epel-release glusterfs-api-devel glusterfs-devel libcephfs-devel
      - yum-builddep -y samba
      - ./localbuild -bb samba.spec
  github_release:
    image: plugins/github-release
    files:
      - "*.rpm"
    checksum:
      - md5
    secrets: [github_token]
    when:
       event: [tag]
